version: '3.8'
services:
  postgres_api:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    container_name: postgres_api
    networks:
      some_network:
        aliases:
          - database
          - localhost
  api_quick:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres_api
    links:
      - postgres_api:postgres_api
    container_name: api_quick
    networks:
      - some_network
networks:
  some_network: